2021-10-02 23:44:58 database: flush
org.h2.message.DbException: Error General : "java.lang.IllegalStateException: The file is locked: nio:C:/Users/profesorado/Desktop/UT10_ProyectoBaseH2/UT10_ProyectoBaseH2/proyectobase.h2db.mv.db [1.4.200/7]"
General error: "java.lang.IllegalStateException: The file is locked: nio:C:/Users/profesorado/Desktop/UT10_ProyectoBaseH2/UT10_ProyectoBaseH2/proyectobase.h2db.mv.db [1.4.200/7]" [50000-200]
	at org.h2.message.DbException.get(DbException.java:194)
	at org.h2.message.DbException.convert(DbException.java:347)
	at org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:93)
	at org.h2.mvstore.MVStore.handleException(MVStore.java:2877)
	at org.h2.mvstore.MVStore.panic(MVStore.java:481)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:402)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:3579)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:170)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:103)
	at org.h2.engine.Database.getPageStore(Database.java:2659)
	at org.h2.engine.Database.open(Database.java:675)
	at org.h2.engine.Database.openDatabase(Database.java:307)
	at org.h2.engine.Database.<init>(Database.java:301)
	at org.h2.engine.Engine.openSession(Engine.java:74)
	at org.h2.engine.Engine.openSession(Engine.java:192)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:171)
	at org.h2.engine.Engine.createSession(Engine.java:166)
	at org.h2.engine.Engine.createSession(Engine.java:29)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:340)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:173)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at ejemplo.Aplicacion.main(Aplicacion.java:75)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: Error General : "java.lang.IllegalStateException: The file is locked: nio:C:/Users/profesorado/Desktop/UT10_ProyectoBaseH2/UT10_ProyectoBaseH2/proyectobase.h2db.mv.db [1.4.200/7]"
General error: "java.lang.IllegalStateException: The file is locked: nio:C:/Users/profesorado/Desktop/UT10_ProyectoBaseH2/UT10_ProyectoBaseH2/proyectobase.h2db.mv.db [1.4.200/7]" [50000-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:505)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 25 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:C:/Users/profesorado/Desktop/UT10_ProyectoBaseH2/UT10_ProyectoBaseH2/proyectobase.h2db.mv.db [1.4.200/7]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:950)
	at org.h2.mvstore.FileStore.open(FileStore.java:172)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:381)
	... 19 more
2021-10-02 23:45:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "PRODUCTO" no encontrada
Table "PRODUCTO" not found; SQL statement:
SELECT id,nombre,precio FROM producto [42102-200]
2021-10-02 23:48:51 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "PRODUCTO" no encontrada
Table "PRODUCTO" not found; SQL statement:
SELECT id,nombre,precio FROM producto [42102-200]
2021-10-03 18:48:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLDataException: Conversi√≥n de datos fallida, convirtiendo "Cazarecompensas"
Data conversion error converting "Cazarecompensas" [22018-200]
2021-10-03 18:49:53 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Columna "descripcion" no encontrada
Column "descripcion" not found [42122-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:453)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.jdbc.JdbcResultSet.getColumnIndex(JdbcResultSet.java:3195)
	at org.h2.jdbc.JdbcResultSet.get(JdbcResultSet.java:3268)
	at org.h2.jdbc.JdbcResultSet.getDouble(JdbcResultSet.java:752)
	at ejemplo.Aplicacion.main(Aplicacion.java:107)
2021-10-05 09:47:32 database: flush
org.h2.message.DbException: Error General : "java.lang.IllegalStateException: The file is locked: nio:D:/Dropbox/miParticularPROG/Tema10/UT10_ProyectoBaseH2/UT10_ProyectoBaseH2/proyectobase.h2db.mv.db [1.4.200/7]"
General error: "java.lang.IllegalStateException: The file is locked: nio:D:/Dropbox/miParticularPROG/Tema10/UT10_ProyectoBaseH2/UT10_ProyectoBaseH2/proyectobase.h2db.mv.db [1.4.200/7]" [50000-200]
	at org.h2.message.DbException.get(DbException.java:194)
	at org.h2.message.DbException.convert(DbException.java:347)
	at org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:93)
	at org.h2.mvstore.MVStore.handleException(MVStore.java:2877)
	at org.h2.mvstore.MVStore.panic(MVStore.java:481)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:402)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:3579)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:170)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:103)
	at org.h2.engine.Database.getPageStore(Database.java:2659)
	at org.h2.engine.Database.open(Database.java:675)
	at org.h2.engine.Database.openDatabase(Database.java:307)
	at org.h2.engine.Database.<init>(Database.java:301)
	at org.h2.engine.Engine.openSession(Engine.java:74)
	at org.h2.engine.Engine.openSession(Engine.java:192)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:171)
	at org.h2.engine.Engine.createSession(Engine.java:166)
	at org.h2.engine.Engine.createSession(Engine.java:29)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:340)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:173)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at ejemplo.Aplicacion.main(Aplicacion.java:81)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: Error General : "java.lang.IllegalStateException: The file is locked: nio:D:/Dropbox/miParticularPROG/Tema10/UT10_ProyectoBaseH2/UT10_ProyectoBaseH2/proyectobase.h2db.mv.db [1.4.200/7]"
General error: "java.lang.IllegalStateException: The file is locked: nio:D:/Dropbox/miParticularPROG/Tema10/UT10_ProyectoBaseH2/UT10_ProyectoBaseH2/proyectobase.h2db.mv.db [1.4.200/7]" [50000-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:505)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 25 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:D:/Dropbox/miParticularPROG/Tema10/UT10_ProyectoBaseH2/UT10_ProyectoBaseH2/proyectobase.h2db.mv.db [1.4.200/7]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:950)
	at org.h2.mvstore.FileStore.open(FileStore.java:172)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:381)
	... 19 more
2021-10-05 10:02:05 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Error de Sintaxis en sentencia SQL "UPDATE NAVE SET DESCRIPCION = 'CUCU' WHERE IDNAVE 1[*]"
Syntax error in SQL statement "UPDATE NAVE SET DESCRIPCION = 'CUCU' WHERE IDNAVE 1[*]"; SQL statement:
UPDATE NAVE SET DESCRIPCION = 'CUCU' WHERE IDNAVE 1 [42000-200]
2021-10-05 10:04:55 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Columna "descripcion" no encontrada
Column "descripcion" not found [42122-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:453)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.jdbc.JdbcResultSet.getColumnIndex(JdbcResultSet.java:3195)
	at org.h2.jdbc.JdbcResultSet.get(JdbcResultSet.java:3268)
	at org.h2.jdbc.JdbcResultSet.getString(JdbcResultSet.java:316)
	at ejemplo.Aplicacion.consultarPersonaje(Aplicacion.java:220)
	at ejemplo.Aplicacion.main(Aplicacion.java:117)
2021-10-05 10:05:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Columna "descripcion" no encontrada
Column "descripcion" not found [42122-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:453)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.jdbc.JdbcResultSet.getColumnIndex(JdbcResultSet.java:3195)
	at org.h2.jdbc.JdbcResultSet.get(JdbcResultSet.java:3268)
	at org.h2.jdbc.JdbcResultSet.getString(JdbcResultSet.java:316)
	at ejemplo.Aplicacion.consultarPersonaje(Aplicacion.java:220)
	at ejemplo.Aplicacion.main(Aplicacion.java:117)
2021-10-05 10:06:26 database: flush
org.h2.message.DbException: Error General : "java.lang.IllegalStateException: The file is locked: nio:D:/Dropbox/miParticularPROG/Tema10/UT10_ProyectoBaseH2/UT10_ProyectoBaseH2/proyectobase.h2db.mv.db [1.4.200/7]"
General error: "java.lang.IllegalStateException: The file is locked: nio:D:/Dropbox/miParticularPROG/Tema10/UT10_ProyectoBaseH2/UT10_ProyectoBaseH2/proyectobase.h2db.mv.db [1.4.200/7]" [50000-200]
	at org.h2.message.DbException.get(DbException.java:194)
	at org.h2.message.DbException.convert(DbException.java:347)
	at org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:93)
	at org.h2.mvstore.MVStore.handleException(MVStore.java:2877)
	at org.h2.mvstore.MVStore.panic(MVStore.java:481)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:402)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:3579)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:170)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:103)
	at org.h2.engine.Database.getPageStore(Database.java:2659)
	at org.h2.engine.Database.open(Database.java:675)
	at org.h2.engine.Database.openDatabase(Database.java:307)
	at org.h2.engine.Database.<init>(Database.java:301)
	at org.h2.engine.Engine.openSession(Engine.java:74)
	at org.h2.engine.Engine.openSession(Engine.java:192)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:171)
	at org.h2.engine.Engine.createSession(Engine.java:166)
	at org.h2.engine.Engine.createSession(Engine.java:29)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:340)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:173)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at ejemplo.Aplicacion.main(Aplicacion.java:81)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: Error General : "java.lang.IllegalStateException: The file is locked: nio:D:/Dropbox/miParticularPROG/Tema10/UT10_ProyectoBaseH2/UT10_ProyectoBaseH2/proyectobase.h2db.mv.db [1.4.200/7]"
General error: "java.lang.IllegalStateException: The file is locked: nio:D:/Dropbox/miParticularPROG/Tema10/UT10_ProyectoBaseH2/UT10_ProyectoBaseH2/proyectobase.h2db.mv.db [1.4.200/7]" [50000-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:505)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 25 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:D:/Dropbox/miParticularPROG/Tema10/UT10_ProyectoBaseH2/UT10_ProyectoBaseH2/proyectobase.h2db.mv.db [1.4.200/7]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:950)
	at org.h2.mvstore.FileStore.open(FileStore.java:172)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:381)
	... 19 more
2021-10-05 10:07:04 database: wrong user or password; user: "SA"
org.h2.message.DbException: Nombre de usuario √≥ password incorrecto
Wrong user name or password [28000-200]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.engine.Engine.openSession(Engine.java:131)
	at org.h2.engine.Engine.openSession(Engine.java:192)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:171)
	at org.h2.engine.Engine.createSession(Engine.java:166)
	at org.h2.engine.Engine.createSession(Engine.java:29)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:340)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:173)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at org.h2.util.JdbcUtils.getConnection(JdbcUtils.java:309)
	at org.h2.util.JdbcUtils.getConnection(JdbcUtils.java:289)
	at org.h2.server.web.WebServer.getConnection(WebServer.java:785)
	at org.h2.server.web.WebApp.login(WebApp.java:1008)
	at org.h2.server.web.WebApp.process(WebApp.java:223)
	at org.h2.server.web.WebApp.processRequest(WebApp.java:173)
	at org.h2.server.web.WebThread.process(WebThread.java:139)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.h2.jdbc.JdbcSQLInvalidAuthorizationSpecException: Nombre de usuario √≥ password incorrecto
Wrong user name or password [28000-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:461)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 21 more
2021-10-18 13:00:15 database: flush
org.h2.message.DbException: Error General : "java.lang.IllegalStateException: The file is locked: nio:D:/Dropbox/miParticularPROG/Tema10/UT10_ProyectoBaseH2_alumnado/UT10_ProyectoBaseH2_alumnado/proyectobase.h2db.mv.db [1.4.200/7]"
General error: "java.lang.IllegalStateException: The file is locked: nio:D:/Dropbox/miParticularPROG/Tema10/UT10_ProyectoBaseH2_alumnado/UT10_ProyectoBaseH2_alumnado/proyectobase.h2db.mv.db [1.4.200/7]" [50000-200]
	at org.h2.message.DbException.get(DbException.java:194)
	at org.h2.message.DbException.convert(DbException.java:347)
	at org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:93)
	at org.h2.mvstore.MVStore.handleException(MVStore.java:2877)
	at org.h2.mvstore.MVStore.panic(MVStore.java:481)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:402)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:3579)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:170)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:103)
	at org.h2.engine.Database.getPageStore(Database.java:2659)
	at org.h2.engine.Database.open(Database.java:675)
	at org.h2.engine.Database.openDatabase(Database.java:307)
	at org.h2.engine.Database.<init>(Database.java:301)
	at org.h2.engine.Engine.openSession(Engine.java:74)
	at org.h2.engine.Engine.openSession(Engine.java:192)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:171)
	at org.h2.engine.Engine.createSession(Engine.java:166)
	at org.h2.engine.Engine.createSession(Engine.java:29)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:340)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:173)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at ejemplo.Aplicacion.main(Aplicacion.java:85)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: Error General : "java.lang.IllegalStateException: The file is locked: nio:D:/Dropbox/miParticularPROG/Tema10/UT10_ProyectoBaseH2_alumnado/UT10_ProyectoBaseH2_alumnado/proyectobase.h2db.mv.db [1.4.200/7]"
General error: "java.lang.IllegalStateException: The file is locked: nio:D:/Dropbox/miParticularPROG/Tema10/UT10_ProyectoBaseH2_alumnado/UT10_ProyectoBaseH2_alumnado/proyectobase.h2db.mv.db [1.4.200/7]" [50000-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:505)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 25 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:D:/Dropbox/miParticularPROG/Tema10/UT10_ProyectoBaseH2_alumnado/UT10_ProyectoBaseH2_alumnado/proyectobase.h2db.mv.db [1.4.200/7]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:950)
	at org.h2.mvstore.FileStore.open(FileStore.java:172)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:381)
	... 19 more
2022-05-18 14:23:31 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Error de Sintaxis en sentencia SQL "

CREATE TABLE IF NOT EXIST[*] NAVE(
IDNAVE INT PRIMARY KEY
NOMBRE STRING
MOTORES INT);

CREATE TABLE IF NOT EXIST PERSONAJE(
CODIGO INT PRIMARY KEY
NOMBRE STRING
DESCRIPCION STRING
TIPO STRING);

CREATE TABLE IF NOR EXIST PILOTA(
CODPERSONAJE INT
CODNAVE INT
FECHA DATE
NAVESABATIDAS INT
CONSTRAINT PIL_CODP_FK FOREIGN KEY PIL_CODP_FK(CODPERSONAJE) REFERENCES NAVE(IDNAVE)
CONSTRAINT PIL_CODN_FK FOREIGN KEY PIL_CODN_FK(CODNAVE) REFERENCES PERSONAJE(CODIGO)
PRIMARY KEY PIL_PK (FECHA, CODPERSONAJE, CODNAVE));


"; se esperaba "EXISTS"
Syntax error in SQL statement "

CREATE TABLE IF NOT EXIST[*] NAVE(
IDNAVE INT PRIMARY KEY
NOMBRE STRING
MOTORES INT);

CREATE TABLE IF NOT EXIST PERSONAJE(
CODIGO INT PRIMARY KEY
NOMBRE STRING
DESCRIPCION STRING
TIPO STRING);

CREATE TABLE IF NOR EXIST PILOTA(
CODPERSONAJE INT
CODNAVE INT
FECHA DATE
NAVESABATIDAS INT
CONSTRAINT PIL_CODP_FK FOREIGN KEY PIL_CODP_FK(CODPERSONAJE) REFERENCES NAVE(IDNAVE)
CONSTRAINT PIL_CODN_FK FOREIGN KEY PIL_CODN_FK(CODNAVE) REFERENCES PERSONAJE(CODIGO)
PRIMARY KEY PIL_PK (FECHA, CODPERSONAJE, CODNAVE));


"; expected "EXISTS"; SQL statement:


CREATE TABLE IF NOT EXIST NAVE(
idnave int primary key
nombre String
motores int);

CREATE TABLE IF NOT EXIST PERSONAJE(
codigo int primary key
nombre String
descripcion String
tipo String);

CREATE TABLE IF NOR EXIST PILOTA(
codpersonaje int
codnave int
fecha date
navesabatidas int
CONSTRAINT pil_codp_fk FOREIGN KEY pil_codp_fk(codpersonaje) REFERENCES NAVE(idnave)
CONSTRAINT pil_codn_fk FOREIGN KEY pil_codn_fk(codnave) REFERENCES PERSONAJE(codigo)
PRIMARY KEY pil_pk (fecha, codpersonaje, codnave));


 [42001-200]
2022-05-18 14:24:04 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Error de Sintaxis en sentencia SQL "

CREATE TABLE IF NOT EXIST[*] NAVE(
IDNAVE INT PRIMARY KEY
NOMBRE STRING
MOTORES INT)

CREATE TABLE IF NOT EXIST PERSONAJE(
CODIGO INT PRIMARY KEY
NOMBRE STRING
DESCRIPCION STRING
TIPO STRING)

CREATE TABLE IF NOR EXIST PILOTA(
CODPERSONAJE INT
CODNAVE INT
FECHA DATE
NAVESABATIDAS INT
CONSTRAINT PIL_CODP_FK FOREIGN KEY PIL_CODP_FK(CODPERSONAJE) REFERENCES NAVE(IDNAVE)
CONSTRAINT PIL_CODN_FK FOREIGN KEY PIL_CODN_FK(CODNAVE) REFERENCES PERSONAJE(CODIGO)
PRIMARY KEY PIL_PK (FECHA, CODPERSONAJE, CODNAVE));


"; se esperaba "EXISTS"
Syntax error in SQL statement "

CREATE TABLE IF NOT EXIST[*] NAVE(
IDNAVE INT PRIMARY KEY
NOMBRE STRING
MOTORES INT)

CREATE TABLE IF NOT EXIST PERSONAJE(
CODIGO INT PRIMARY KEY
NOMBRE STRING
DESCRIPCION STRING
TIPO STRING)

CREATE TABLE IF NOR EXIST PILOTA(
CODPERSONAJE INT
CODNAVE INT
FECHA DATE
NAVESABATIDAS INT
CONSTRAINT PIL_CODP_FK FOREIGN KEY PIL_CODP_FK(CODPERSONAJE) REFERENCES NAVE(IDNAVE)
CONSTRAINT PIL_CODN_FK FOREIGN KEY PIL_CODN_FK(CODNAVE) REFERENCES PERSONAJE(CODIGO)
PRIMARY KEY PIL_PK (FECHA, CODPERSONAJE, CODNAVE));


"; expected "EXISTS"; SQL statement:


CREATE TABLE IF NOT EXIST NAVE(
idnave int primary key
nombre String
motores int)

CREATE TABLE IF NOT EXIST PERSONAJE(
codigo int primary key
nombre String
descripcion String
tipo String)

CREATE TABLE IF NOR EXIST PILOTA(
codpersonaje int
codnave int
fecha date
navesabatidas int
CONSTRAINT pil_codp_fk FOREIGN KEY pil_codp_fk(codpersonaje) REFERENCES NAVE(idnave)
CONSTRAINT pil_codn_fk FOREIGN KEY pil_codn_fk(codnave) REFERENCES PERSONAJE(codigo)
PRIMARY KEY pil_pk (fecha, codpersonaje, codnave));


 [42001-200]
2022-05-18 14:30:36 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Error de Sintaxis en sentencia SQL "

CREATE TABLE IF NOT EXIST[*] NAVE(
IDNAVE INT PRIMARY KEY,
NOMBRE VARCHAR (100),
MOTORES INT);

CREATE TABLE IF NOT EXIST PERSONAJE(
CODIGO INT PRIMARY KEY,
NOMBRE VARCHAR (100),
DESCRIPCION VARCHAR (100),
TIPO VARCHAR (100));

CREATE TABLE IF NOR EXIST PILOTA(
CODPERSONAJE INT,
CODNAVE INT,
FECHA DATE,
NAVESABATIDAS INT,
CONSTRAINT PIL_CODP_FK FOREIGN KEY PIL_CODP_FK(CODPERSONAJE) REFERENCES NAVE(IDNAVE),
CONSTRAINT PIL_CODN_FK FOREIGN KEY PIL_CODN_FK(CODNAVE) REFERENCES PERSONAJE(CODIGO),
PRIMARY KEY PIL_PK (FECHA, CODPERSONAJE, CODNAVE));


"; se esperaba "EXISTS"
Syntax error in SQL statement "

CREATE TABLE IF NOT EXIST[*] NAVE(
IDNAVE INT PRIMARY KEY,
NOMBRE VARCHAR (100),
MOTORES INT);

CREATE TABLE IF NOT EXIST PERSONAJE(
CODIGO INT PRIMARY KEY,
NOMBRE VARCHAR (100),
DESCRIPCION VARCHAR (100),
TIPO VARCHAR (100));

CREATE TABLE IF NOR EXIST PILOTA(
CODPERSONAJE INT,
CODNAVE INT,
FECHA DATE,
NAVESABATIDAS INT,
CONSTRAINT PIL_CODP_FK FOREIGN KEY PIL_CODP_FK(CODPERSONAJE) REFERENCES NAVE(IDNAVE),
CONSTRAINT PIL_CODN_FK FOREIGN KEY PIL_CODN_FK(CODNAVE) REFERENCES PERSONAJE(CODIGO),
PRIMARY KEY PIL_PK (FECHA, CODPERSONAJE, CODNAVE));


"; expected "EXISTS"; SQL statement:


CREATE TABLE IF NOT EXIST NAVE(
idnave int primary key,
nombre varchar (100),
motores int);

CREATE TABLE IF NOT EXIST PERSONAJE(
codigo int primary key,
nombre varchar (100),
descripcion varchar (100),
tipo varchar (100));

CREATE TABLE IF NOR EXIST PILOTA(
codpersonaje int,
codnave int,
fecha date,
navesabatidas int,
CONSTRAINT pil_codp_fk FOREIGN KEY pil_codp_fk(codpersonaje) REFERENCES NAVE(idnave),
CONSTRAINT pil_codn_fk FOREIGN KEY pil_codn_fk(codnave) REFERENCES PERSONAJE(codigo),
PRIMARY KEY pil_pk (fecha, codpersonaje, codnave));


 [42001-200]
2022-05-18 14:34:27 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Error de Sintaxis en sentencia SQL "

CREATE TABLE IF NOT EXISTS PILOTA(
CODPERSONAJE INT,
CODNAVE INT,
FECHA DATE,
NAVESABATIDAS INT,
CONSTRAINT PIL_CODP_FK FOREIGN KEY PIL_CODP_FK[*](CODPERSONAJE) REFERENCES NAVE(IDNAVE),
CONSTRAINT PIL_CODN_FK FOREIGN KEY PIL_CODN_FK(CODNAVE) REFERENCES PERSONAJE(CODIGO),
PRIMARY KEY PIL_PK (FECHA, CODPERSONAJE, CODNAVE));


"; se esperaba "("
Syntax error in SQL statement "

CREATE TABLE IF NOT EXISTS PILOTA(
CODPERSONAJE INT,
CODNAVE INT,
FECHA DATE,
NAVESABATIDAS INT,
CONSTRAINT PIL_CODP_FK FOREIGN KEY PIL_CODP_FK[*](CODPERSONAJE) REFERENCES NAVE(IDNAVE),
CONSTRAINT PIL_CODN_FK FOREIGN KEY PIL_CODN_FK(CODNAVE) REFERENCES PERSONAJE(CODIGO),
PRIMARY KEY PIL_PK (FECHA, CODPERSONAJE, CODNAVE));


"; expected "("; SQL statement:


CREATE TABLE IF NOT EXISTS PILOTA(
codpersonaje int,
codnave int,
fecha date,
navesabatidas int,
CONSTRAINT pil_codp_fk FOREIGN KEY pil_codp_fk(codpersonaje) REFERENCES NAVE(idnave),
CONSTRAINT pil_codn_fk FOREIGN KEY pil_codn_fk(codnave) REFERENCES PERSONAJE(codigo),
PRIMARY KEY pil_pk (fecha, codpersonaje, codnave));


 [42001-200]
2022-05-18 15:28:15 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Error de Sintaxis en sentencia SQL "

CREATE TABLE IF NOT EXISTS PILOTA(
CODPERSONAJE INT,
CODNAVE INT,
FECHA DATE,
NAVESABATIDAS INT,
PRIMARY KEY PIL_PK[*] (FECHA, CODPERSONAJE, CODNAVE),
CONSTRAINT PIL_CODP_FK FOREIGN KEY PIL_CODP_FK(CODPERSONAJE) REFERENCES PERSONAJE(CODIGO) ON DELETE CASCADE ON UPDATE CASCADE,
CONSTRAINT PIL_CODN_FK FOREIGN KEY PIL_CODN_FK(CODNAVE) REFERENCES NAVE(IDNAVE) ON DELETE CASCADE ON UPDATE CASCADE);"; se esperaba "HASH, ("
Syntax error in SQL statement "

CREATE TABLE IF NOT EXISTS PILOTA(
CODPERSONAJE INT,
CODNAVE INT,
FECHA DATE,
NAVESABATIDAS INT,
PRIMARY KEY PIL_PK[*] (FECHA, CODPERSONAJE, CODNAVE),
CONSTRAINT PIL_CODP_FK FOREIGN KEY PIL_CODP_FK(CODPERSONAJE) REFERENCES PERSONAJE(CODIGO) ON DELETE CASCADE ON UPDATE CASCADE,
CONSTRAINT PIL_CODN_FK FOREIGN KEY PIL_CODN_FK(CODNAVE) REFERENCES NAVE(IDNAVE) ON DELETE CASCADE ON UPDATE CASCADE);"; expected "HASH, ("; SQL statement:


CREATE TABLE IF NOT EXISTS PILOTA(
codpersonaje int,
codnave int,
fecha date,
navesabatidas int,
PRIMARY KEY pil_pk (fecha, codpersonaje, codnave),
CONSTRAINT pil_codp_fk FOREIGN KEY pil_codp_fk(codpersonaje) REFERENCES PERSONAJE(codigo) ON DELETE CASCADE ON UPDATE CASCADE,
CONSTRAINT pil_codn_fk FOREIGN KEY pil_codn_fk(codnave) REFERENCES NAVE(idnave) ON DELETE CASCADE ON UPDATE CASCADE); [42001-200]
2022-05-18 15:29:27 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Error de Sintaxis en sentencia SQL "

CREATE TABLE IF NOT EXISTS PILOTA(
CODPERSONAJE INT,
CODNAVE INT,
FECHA DATE,
NAVESABATIDAS INT,
PRIMARY KEY PIL_PK[*] (FECHA, CODPERSONAJE, CODNAVE),
CONSTRAINT PIL_CODP_FK FOREIGN KEY PIL_CODP_FK(CODPERSONAJE) REFERENCES PERSONAJE(CODIGO) ON DELETE CASCADE ON UPDATE CASCADE,
CONSTRAINT PIL_CODN_FK FOREIGN KEY PIL_CODN_FK(CODNAVE) REFERENCES NAVE(IDNAVE) ON DELETE CASCADE ON UPDATE CASCADE);"; se esperaba "HASH, ("
Syntax error in SQL statement "

CREATE TABLE IF NOT EXISTS PILOTA(
CODPERSONAJE INT,
CODNAVE INT,
FECHA DATE,
NAVESABATIDAS INT,
PRIMARY KEY PIL_PK[*] (FECHA, CODPERSONAJE, CODNAVE),
CONSTRAINT PIL_CODP_FK FOREIGN KEY PIL_CODP_FK(CODPERSONAJE) REFERENCES PERSONAJE(CODIGO) ON DELETE CASCADE ON UPDATE CASCADE,
CONSTRAINT PIL_CODN_FK FOREIGN KEY PIL_CODN_FK(CODNAVE) REFERENCES NAVE(IDNAVE) ON DELETE CASCADE ON UPDATE CASCADE);"; expected "HASH, ("; SQL statement:


CREATE TABLE IF NOT EXISTS PILOTA(
codpersonaje int,
codnave int,
fecha date,
navesabatidas int,
PRIMARY KEY pil_pk (fecha, codpersonaje, codnave),
CONSTRAINT pil_codp_fk FOREIGN KEY pil_codp_fk(codpersonaje) REFERENCES PERSONAJE(codigo) ON DELETE CASCADE ON UPDATE CASCADE,
CONSTRAINT pil_codn_fk FOREIGN KEY pil_codn_fk(codnave) REFERENCES NAVE(idnave) ON DELETE CASCADE ON UPDATE CASCADE); [42001-200]
2022-05-18 15:37:37 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Error de Sintaxis en sentencia SQL "

CREATE TABLE IF NOT EXISTS PILOTA(
CODPERSONAJE INT,
CODNAVE INT,
FECHA DATETIME,
NAVESABATIDAS INT,
PRIMARY KEY PIL_PK[*] (FECHA, CODPERSONAJE, CODNAVE),
CONSTRAINT PIL_CODP_FK FOREIGN KEY PIL_CODP_FK(CODPERSONAJE) REFERENCES PERSONAJE(CODIGO) ON DELETE CASCADE ON UPDATE CASCADE,
CONSTRAINT PIL_CODN_FK FOREIGN KEY PIL_CODN_FK(CODNAVE) REFERENCES NAVE(IDNAVE) ON DELETE CASCADE ON UPDATE CASCADE);"; se esperaba "HASH, ("
Syntax error in SQL statement "

CREATE TABLE IF NOT EXISTS PILOTA(
CODPERSONAJE INT,
CODNAVE INT,
FECHA DATETIME,
NAVESABATIDAS INT,
PRIMARY KEY PIL_PK[*] (FECHA, CODPERSONAJE, CODNAVE),
CONSTRAINT PIL_CODP_FK FOREIGN KEY PIL_CODP_FK(CODPERSONAJE) REFERENCES PERSONAJE(CODIGO) ON DELETE CASCADE ON UPDATE CASCADE,
CONSTRAINT PIL_CODN_FK FOREIGN KEY PIL_CODN_FK(CODNAVE) REFERENCES NAVE(IDNAVE) ON DELETE CASCADE ON UPDATE CASCADE);"; expected "HASH, ("; SQL statement:


CREATE TABLE IF NOT EXISTS PILOTA(
codpersonaje int,
codnave int,
fecha datetime,
navesabatidas int,
PRIMARY KEY pil_pk (fecha, codpersonaje, codnave),
CONSTRAINT pil_codp_fk FOREIGN KEY pil_codp_fk(codpersonaje) REFERENCES PERSONAJE(codigo) ON DELETE CASCADE ON UPDATE CASCADE,
CONSTRAINT pil_codn_fk FOREIGN KEY pil_codn_fk(codnave) REFERENCES NAVE(idnave) ON DELETE CASCADE ON UPDATE CASCADE); [42001-200]
2022-05-18 15:39:43 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Error de Sintaxis en sentencia SQL "

CREATE TABLE IF NOT EXISTS PILOTA(
CODPERSONAJE INT,
CODNAVE INT,
FECHA DATETIME,
NAVESABATIDAS INT,
PRIMARY KEY PIL_PK[*] (FECHA, CODPERSONAJE, CODNAVE),
CONSTRAINT PIL_CODP_FK FOREIGN KEY PIL_CODP_FK(CODPERSONAJE) REFERENCES PERSONAJE(CODIGO) ON DELETE CASCADE ON UPDATE CASCADE,
CONSTRAINT PIL_CODN_FK FOREIGN KEY PIL_CODN_FK(CODNAVE) REFERENCES NAVE(IDNAVE) ON DELETE CASCADE ON UPDATE CASCADE);"; se esperaba "HASH, ("
Syntax error in SQL statement "

CREATE TABLE IF NOT EXISTS PILOTA(
CODPERSONAJE INT,
CODNAVE INT,
FECHA DATETIME,
NAVESABATIDAS INT,
PRIMARY KEY PIL_PK[*] (FECHA, CODPERSONAJE, CODNAVE),
CONSTRAINT PIL_CODP_FK FOREIGN KEY PIL_CODP_FK(CODPERSONAJE) REFERENCES PERSONAJE(CODIGO) ON DELETE CASCADE ON UPDATE CASCADE,
CONSTRAINT PIL_CODN_FK FOREIGN KEY PIL_CODN_FK(CODNAVE) REFERENCES NAVE(IDNAVE) ON DELETE CASCADE ON UPDATE CASCADE);"; expected "HASH, ("; SQL statement:


CREATE TABLE IF NOT EXISTS PILOTA(
codpersonaje int,
codnave int,
fecha datetime,
navesabatidas int,
PRIMARY KEY pil_pk (fecha, codpersonaje, codnave),
CONSTRAINT pil_codp_fk FOREIGN KEY pil_codp_fk(codpersonaje) REFERENCES PERSONAJE(codigo) ON DELETE CASCADE ON UPDATE CASCADE,
CONSTRAINT pil_codn_fk FOREIGN KEY pil_codn_fk(codnave) REFERENCES NAVE(idnave) ON DELETE CASCADE ON UPDATE CASCADE); [42001-200]
2022-05-18 18:35:27 database: wrong user or password; user: "SA"
org.h2.message.DbException: Nombre de usuario √≥ password incorrecto
Wrong user name or password [28000-200]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.engine.Engine.openSession(Engine.java:131)
	at org.h2.engine.Engine.openSession(Engine.java:192)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:171)
	at org.h2.engine.Engine.createSession(Engine.java:166)
	at org.h2.engine.Engine.createSession(Engine.java:29)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:340)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:173)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at org.h2.util.JdbcUtils.getConnection(JdbcUtils.java:309)
	at org.h2.util.JdbcUtils.getConnection(JdbcUtils.java:289)
	at org.h2.server.web.WebServer.getConnection(WebServer.java:785)
	at org.h2.server.web.WebApp.login(WebApp.java:1008)
	at org.h2.server.web.WebApp.process(WebApp.java:223)
	at org.h2.server.web.WebApp.processRequest(WebApp.java:173)
	at org.h2.server.web.WebThread.process(WebThread.java:139)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.h2.jdbc.JdbcSQLInvalidAuthorizationSpecException: Nombre de usuario √≥ password incorrecto
Wrong user name or password [28000-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:461)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 21 more
2022-05-18 18:58:21 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "PERSONA" no encontrada
Table "PERSONA" not found; SQL statement:
select codigo,nombre,descripcion from persona [42102-200]
2022-05-18 19:27:51 database: flush
org.h2.message.DbException: Error General : "java.lang.IllegalStateException: The file is locked: nio:/home/arioch/Documentos/Proyectos_NetBeans/UT10_ProyectoBaseH2_alumnado/proyectobase.h2db.mv.db [1.4.200/7]"
General error: "java.lang.IllegalStateException: The file is locked: nio:/home/arioch/Documentos/Proyectos_NetBeans/UT10_ProyectoBaseH2_alumnado/proyectobase.h2db.mv.db [1.4.200/7]" [50000-200]
	at org.h2.message.DbException.get(DbException.java:194)
	at org.h2.message.DbException.convert(DbException.java:347)
	at org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:93)
	at org.h2.mvstore.MVStore.handleException(MVStore.java:2877)
	at org.h2.mvstore.MVStore.panic(MVStore.java:481)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:402)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:3579)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:170)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:103)
	at org.h2.engine.Database.getPageStore(Database.java:2659)
	at org.h2.engine.Database.open(Database.java:675)
	at org.h2.engine.Database.openDatabase(Database.java:307)
	at org.h2.engine.Database.<init>(Database.java:301)
	at org.h2.engine.Engine.openSession(Engine.java:74)
	at org.h2.engine.Engine.openSession(Engine.java:192)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:171)
	at org.h2.engine.Engine.createSession(Engine.java:166)
	at org.h2.engine.Engine.createSession(Engine.java:29)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:340)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:173)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at ejemplo.Aplicacion.main(Aplicacion.java:85)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: Error General : "java.lang.IllegalStateException: The file is locked: nio:/home/arioch/Documentos/Proyectos_NetBeans/UT10_ProyectoBaseH2_alumnado/proyectobase.h2db.mv.db [1.4.200/7]"
General error: "java.lang.IllegalStateException: The file is locked: nio:/home/arioch/Documentos/Proyectos_NetBeans/UT10_ProyectoBaseH2_alumnado/proyectobase.h2db.mv.db [1.4.200/7]" [50000-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:505)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 25 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:/home/arioch/Documentos/Proyectos_NetBeans/UT10_ProyectoBaseH2_alumnado/proyectobase.h2db.mv.db [1.4.200/7]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:950)
	at org.h2.mvstore.FileStore.open(FileStore.java:172)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:381)
	... 19 more
2022-05-18 19:28:02 database: flush
org.h2.message.DbException: Error General : "java.lang.IllegalStateException: The file is locked: nio:/home/arioch/Documentos/Proyectos_NetBeans/UT10_ProyectoBaseH2_alumnado/proyectobase.h2db.mv.db [1.4.200/7]"
General error: "java.lang.IllegalStateException: The file is locked: nio:/home/arioch/Documentos/Proyectos_NetBeans/UT10_ProyectoBaseH2_alumnado/proyectobase.h2db.mv.db [1.4.200/7]" [50000-200]
	at org.h2.message.DbException.get(DbException.java:194)
	at org.h2.message.DbException.convert(DbException.java:347)
	at org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:93)
	at org.h2.mvstore.MVStore.handleException(MVStore.java:2877)
	at org.h2.mvstore.MVStore.panic(MVStore.java:481)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:402)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:3579)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:170)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:103)
	at org.h2.engine.Database.getPageStore(Database.java:2659)
	at org.h2.engine.Database.open(Database.java:675)
	at org.h2.engine.Database.openDatabase(Database.java:307)
	at org.h2.engine.Database.<init>(Database.java:301)
	at org.h2.engine.Engine.openSession(Engine.java:74)
	at org.h2.engine.Engine.openSession(Engine.java:192)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:171)
	at org.h2.engine.Engine.createSession(Engine.java:166)
	at org.h2.engine.Engine.createSession(Engine.java:29)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:340)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:173)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at ejemplo.Aplicacion.main(Aplicacion.java:85)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: Error General : "java.lang.IllegalStateException: The file is locked: nio:/home/arioch/Documentos/Proyectos_NetBeans/UT10_ProyectoBaseH2_alumnado/proyectobase.h2db.mv.db [1.4.200/7]"
General error: "java.lang.IllegalStateException: The file is locked: nio:/home/arioch/Documentos/Proyectos_NetBeans/UT10_ProyectoBaseH2_alumnado/proyectobase.h2db.mv.db [1.4.200/7]" [50000-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:505)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 25 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:/home/arioch/Documentos/Proyectos_NetBeans/UT10_ProyectoBaseH2_alumnado/proyectobase.h2db.mv.db [1.4.200/7]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:950)
	at org.h2.mvstore.FileStore.open(FileStore.java:172)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:381)
	... 19 more
2022-05-18 20:28:42 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: Este metodo no esta permitido para una sentencia preparada; en su lugar use una sentencia regular.
This method is not allowed for a prepared statement; use a regular statement instead. [90130-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:505)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:322)
	at ejemplo.Aplicacion.borrarPersonaje(Aplicacion.java:312)
	at ejemplo.Aplicacion.main(Aplicacion.java:143)
2022-05-18 20:57:22 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Error de Sintaxis en sentencia SQL "UPDATE FROM[*] NAVE NOMBRE = HIPOPOTAMO WHERE IDNAVE = '1';"; se esperaba "identifier"
Syntax error in SQL statement "UPDATE FROM[*] NAVE NOMBRE = HIPOPOTAMO WHERE IDNAVE = '1';"; expected "identifier"; SQL statement:
UPDATE FROM NAVE nombre = HIPOPOTAMO WHERE idnave = '1'; [42001-200]
2022-05-18 20:58:31 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Columna "HIPOPOTAMO" no encontrada
Column "HIPOPOTAMO" not found; SQL statement:
UPDATE NAVE SET nombre = HIPOPOTAMO WHERE idnave = '1'; [42122-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:453)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.expression.ExpressionColumn.getColumnException(ExpressionColumn.java:163)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:145)
	at org.h2.command.dml.Update.prepare(Update.java:275)
	at org.h2.command.Parser.prepareCommand(Parser.java:744)
	at org.h2.engine.Session.prepareLocal(Session.java:657)
	at org.h2.engine.Session.prepareCommand(Session.java:595)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1235)
	at org.h2.jdbc.JdbcStatement.executeUpdateInternal(JdbcStatement.java:164)
	at org.h2.jdbc.JdbcStatement.executeUpdate(JdbcStatement.java:126)
	at ejemplo.Aplicacion.modificarNave(Aplicacion.java:305)
	at ejemplo.Aplicacion.main(Aplicacion.java:141)
2022-05-18 21:04:04 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Columna "HIPOPOTAMO" no encontrada
Column "HIPOPOTAMO" not found; SQL statement:
UPDATE NAVE SET nombre = HIPOPOTAMO WHERE idnave = '1'; [42122-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:453)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.expression.ExpressionColumn.getColumnException(ExpressionColumn.java:163)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:145)
	at org.h2.command.dml.Update.prepare(Update.java:275)
	at org.h2.command.Parser.prepareCommand(Parser.java:744)
	at org.h2.engine.Session.prepareLocal(Session.java:657)
	at org.h2.engine.Session.prepareCommand(Session.java:595)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1235)
	at org.h2.jdbc.JdbcStatement.executeUpdateInternal(JdbcStatement.java:164)
	at org.h2.jdbc.JdbcStatement.executeUpdate(JdbcStatement.java:126)
	at ejemplo.Aplicacion.modificarNave(Aplicacion.java:285)
	at ejemplo.Aplicacion.main(Aplicacion.java:141)
2022-05-18 21:06:04 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Columna "HIPOPOTAMO" no encontrada
Column "HIPOPOTAMO" not found; SQL statement:
UPDATE NAVE SET nombre = HIPOPOTAMO WHERE idnave = 1; [42122-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:453)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.expression.ExpressionColumn.getColumnException(ExpressionColumn.java:163)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:145)
	at org.h2.command.dml.Update.prepare(Update.java:275)
	at org.h2.command.Parser.prepareCommand(Parser.java:744)
	at org.h2.engine.Session.prepareLocal(Session.java:657)
	at org.h2.engine.Session.prepareCommand(Session.java:595)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1235)
	at org.h2.jdbc.JdbcStatement.executeUpdateInternal(JdbcStatement.java:164)
	at org.h2.jdbc.JdbcStatement.executeUpdate(JdbcStatement.java:126)
	at ejemplo.Aplicacion.modificarNave(Aplicacion.java:285)
	at ejemplo.Aplicacion.main(Aplicacion.java:141)
2022-05-18 21:30:25 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Columna "HIPOPOTAMO" no encontrada
Column "HIPOPOTAMO" not found; SQL statement:
UPDATE NAVE SET nombre=HIPOPOTAMO WHERE idnave = 1; [42122-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:453)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.expression.ExpressionColumn.getColumnException(ExpressionColumn.java:163)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:145)
	at org.h2.command.dml.Update.prepare(Update.java:275)
	at org.h2.command.Parser.prepareCommand(Parser.java:744)
	at org.h2.engine.Session.prepareLocal(Session.java:657)
	at org.h2.engine.Session.prepareCommand(Session.java:595)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1235)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:76)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:352)
	at ejemplo.Aplicacion.modificarNave(Aplicacion.java:282)
	at ejemplo.Aplicacion.main(Aplicacion.java:141)
2022-05-18 21:32:13 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Columna "HIPOPOTAMO" no encontrada
Column "HIPOPOTAMO" not found; SQL statement:
UPDATE NAVE SET nombre=HIPOPOTAMO WHERE idnave = 1; [42122-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:453)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.expression.ExpressionColumn.getColumnException(ExpressionColumn.java:163)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:145)
	at org.h2.command.dml.Update.prepare(Update.java:275)
	at org.h2.command.Parser.prepareCommand(Parser.java:744)
	at org.h2.engine.Session.prepareLocal(Session.java:657)
	at org.h2.engine.Session.prepareCommand(Session.java:595)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1235)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:76)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:352)
	at ejemplo.Aplicacion.modificarNave(Aplicacion.java:282)
	at ejemplo.Aplicacion.main(Aplicacion.java:141)
2022-05-18 21:32:38 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Columna "HIPOPOTAMO" no encontrada
Column "HIPOPOTAMO" not found; SQL statement:
UPDATE NAVE SET nombre=HIPOPOTAMO WHERE idnave = 1; [42122-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:453)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.expression.ExpressionColumn.getColumnException(ExpressionColumn.java:163)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:145)
	at org.h2.command.dml.Update.prepare(Update.java:275)
	at org.h2.command.Parser.prepareCommand(Parser.java:744)
	at org.h2.engine.Session.prepareLocal(Session.java:657)
	at org.h2.engine.Session.prepareCommand(Session.java:595)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1235)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:76)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:352)
	at ejemplo.Aplicacion.modificarNave(Aplicacion.java:282)
	at ejemplo.Aplicacion.main(Aplicacion.java:141)
2022-05-18 21:34:32 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Columna "HIPOPOTAMO" no encontrada
Column "HIPOPOTAMO" not found; SQL statement:
UPDATE NAVE SET nombre=HIPOPOTAMO WHERE idnave = 1; [42122-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:453)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.expression.ExpressionColumn.getColumnException(ExpressionColumn.java:163)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:145)
	at org.h2.command.dml.Update.prepare(Update.java:275)
	at org.h2.command.Parser.prepareCommand(Parser.java:744)
	at org.h2.engine.Session.prepareLocal(Session.java:657)
	at org.h2.engine.Session.prepareCommand(Session.java:595)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1235)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:76)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:352)
	at ejemplo.Aplicacion.modificarNave(Aplicacion.java:282)
	at ejemplo.Aplicacion.main(Aplicacion.java:141)
2022-05-18 21:35:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Columna "HIPOPOTAMO" no encontrada
Column "HIPOPOTAMO" not found; SQL statement:
UPDATE NAVE SET NOMBRE=HIPOPOTAMO WHERE IDNAVE=?; [42122-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:453)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.expression.ExpressionColumn.getColumnException(ExpressionColumn.java:163)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:145)
	at org.h2.command.dml.Update.prepare(Update.java:275)
	at org.h2.command.Parser.prepareCommand(Parser.java:744)
	at org.h2.engine.Session.prepareLocal(Session.java:657)
	at org.h2.engine.Session.prepareCommand(Session.java:595)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1235)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:76)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:352)
	at ejemplo.Aplicacion.modificarNave(Aplicacion.java:282)
	at ejemplo.Aplicacion.main(Aplicacion.java:141)
2022-05-18 21:36:36 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Columna "HIPOPOTAMO" no encontrada
Column "HIPOPOTAMO" not found; SQL statement:
UPDATE NAVE SET NOMBRE=HIPOPOTAMO WHERE IDNAVE=?; [42122-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:453)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.expression.ExpressionColumn.getColumnException(ExpressionColumn.java:163)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:145)
	at org.h2.command.dml.Update.prepare(Update.java:275)
	at org.h2.command.Parser.prepareCommand(Parser.java:744)
	at org.h2.engine.Session.prepareLocal(Session.java:657)
	at org.h2.engine.Session.prepareCommand(Session.java:595)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1235)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:76)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:352)
	at ejemplo.Aplicacion.modificarNave(Aplicacion.java:280)
	at ejemplo.Aplicacion.main(Aplicacion.java:141)
2022-05-18 21:38:25 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Columna "HIPOPOTAMO" no encontrada
Column "HIPOPOTAMO" not found; SQL statement:
UPDATE NAVE SET NOMBRE=HIPOPOTAMO WHERE IDNAVE=?; [42122-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:453)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.expression.ExpressionColumn.getColumnException(ExpressionColumn.java:163)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:145)
	at org.h2.command.dml.Update.prepare(Update.java:275)
	at org.h2.command.Parser.prepareCommand(Parser.java:744)
	at org.h2.engine.Session.prepareLocal(Session.java:657)
	at org.h2.engine.Session.prepareCommand(Session.java:595)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1235)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:76)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:352)
	at ejemplo.Aplicacion.modificarNave(Aplicacion.java:280)
	at ejemplo.Aplicacion.main(Aplicacion.java:141)
2022-05-18 21:39:07 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Columna "HIPOPOTAMO" no encontrada
Column "HIPOPOTAMO" not found; SQL statement:
UPDATE NAVE SET nombre=HIPOPOTAMO WHERE idnave=?; [42122-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:453)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.expression.ExpressionColumn.getColumnException(ExpressionColumn.java:163)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:145)
	at org.h2.command.dml.Update.prepare(Update.java:275)
	at org.h2.command.Parser.prepareCommand(Parser.java:744)
	at org.h2.engine.Session.prepareLocal(Session.java:657)
	at org.h2.engine.Session.prepareCommand(Session.java:595)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1235)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:76)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:352)
	at ejemplo.Aplicacion.modificarNave(Aplicacion.java:280)
	at ejemplo.Aplicacion.main(Aplicacion.java:141)
